on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm test
          cd web-app
          npm install
          cd ..
          npm run build-web
        env:
          CI: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Zip Folder
        run: zip -r mage_${{steps.get_verison.outputs.VERSION}}.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: mage_${{steps.get_verison.outputs.VERSION}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}